// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.16.0
// source: pubsub/pubsub.proto

package pubsub

import (
	msg "github.com/sasidakh/kyu/q/msg"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PublishResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ack *msg.Ack `protobuf:"bytes,1,opt,name=ack,proto3" json:"ack,omitempty"`
}

func (x *PublishResult) Reset() {
	*x = PublishResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pubsub_pubsub_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublishResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResult) ProtoMessage() {}

func (x *PublishResult) ProtoReflect() protoreflect.Message {
	mi := &file_pubsub_pubsub_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResult.ProtoReflect.Descriptor instead.
func (*PublishResult) Descriptor() ([]byte, []int) {
	return file_pubsub_pubsub_proto_rawDescGZIP(), []int{0}
}

func (x *PublishResult) GetAck() *msg.Ack {
	if x != nil {
		return x.Ack
	}
	return nil
}

var File_pubsub_pubsub_proto protoreflect.FileDescriptor

var file_pubsub_pubsub_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x75, 0x62, 0x73, 0x75, 0x62, 0x2f, 0x70, 0x75, 0x62, 0x73, 0x75, 0x62, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x75, 0x62, 0x73, 0x75, 0x62, 0x1a, 0x0f, 0x71,
	0x2f, 0x6d, 0x73, 0x67, 0x2f, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2b,
	0x0a, 0x0d, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x1a, 0x0a, 0x03, 0x61, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x6d,
	0x73, 0x67, 0x2e, 0x41, 0x63, 0x6b, 0x52, 0x03, 0x61, 0x63, 0x6b, 0x32, 0x61, 0x0a, 0x06, 0x50,
	0x75, 0x62, 0x53, 0x75, 0x62, 0x12, 0x2e, 0x0a, 0x07, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68,
	0x12, 0x0c, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x15,
	0x2e, 0x70, 0x75, 0x62, 0x73, 0x75, 0x62, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x27, 0x0a, 0x09, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69,
	0x62, 0x65, 0x12, 0x0a, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x51, 0x75, 0x65, 0x75, 0x65, 0x1a, 0x0c,
	0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x30, 0x01, 0x42, 0x20,
	0x5a, 0x1e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x61, 0x73,
	0x69, 0x64, 0x61, 0x6b, 0x68, 0x2f, 0x6b, 0x79, 0x75, 0x2f, 0x70, 0x75, 0x62, 0x73, 0x75, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pubsub_pubsub_proto_rawDescOnce sync.Once
	file_pubsub_pubsub_proto_rawDescData = file_pubsub_pubsub_proto_rawDesc
)

func file_pubsub_pubsub_proto_rawDescGZIP() []byte {
	file_pubsub_pubsub_proto_rawDescOnce.Do(func() {
		file_pubsub_pubsub_proto_rawDescData = protoimpl.X.CompressGZIP(file_pubsub_pubsub_proto_rawDescData)
	})
	return file_pubsub_pubsub_proto_rawDescData
}

var file_pubsub_pubsub_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pubsub_pubsub_proto_goTypes = []interface{}{
	(*PublishResult)(nil), // 0: pubsub.PublishResult
	(*msg.Ack)(nil),       // 1: msg.Ack
	(*msg.Message)(nil),   // 2: msg.Message
	(*msg.Queue)(nil),     // 3: msg.Queue
}
var file_pubsub_pubsub_proto_depIdxs = []int32{
	1, // 0: pubsub.PublishResult.ack:type_name -> msg.Ack
	2, // 1: pubsub.PubSub.Publish:input_type -> msg.Message
	3, // 2: pubsub.PubSub.Subscribe:input_type -> msg.Queue
	0, // 3: pubsub.PubSub.Publish:output_type -> pubsub.PublishResult
	2, // 4: pubsub.PubSub.Subscribe:output_type -> msg.Message
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pubsub_pubsub_proto_init() }
func file_pubsub_pubsub_proto_init() {
	if File_pubsub_pubsub_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pubsub_pubsub_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublishResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pubsub_pubsub_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pubsub_pubsub_proto_goTypes,
		DependencyIndexes: file_pubsub_pubsub_proto_depIdxs,
		MessageInfos:      file_pubsub_pubsub_proto_msgTypes,
	}.Build()
	File_pubsub_pubsub_proto = out.File
	file_pubsub_pubsub_proto_rawDesc = nil
	file_pubsub_pubsub_proto_goTypes = nil
	file_pubsub_pubsub_proto_depIdxs = nil
}
